name = "trail-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "trail"
database_id = "71944b5b-1645-435d-adcc-65e592dd17f9"

[vars]

[[migrations]]
tag = "v1"
new_sqlite_classes = []
